services:
  pg:
    image: 'bitnami/postgresql'
    ports:
      - '5433:5432'
    environment:
      - POSTGRESQL_USERNAME=postgresql
      - POSTGRESQL_PASSWORD=123
      - POSTGRESQL_DATABASE=biblioteca_test
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
